from app.models.user import User
from app.models.university import University
from app.models.course import Course
from app.models.scholarship import Scholarship
from app.models.lead import Lead
from app.models.student import Student
from app.models.document import Document
from app.models.blog import BlogPost
from app.models.consultation import Consultation
from app.models.testimonial import Testimonial
from app.models.faq import FAQ
